name: price_mvp
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - brotli=1.2.0
  - brotli-bin=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2026.1.4
  - conda-pack=0.9.1
  - contourpy=1.3.2
  - cycler=0.12.1
  - et_xmlfile=2.0.0
  - fonttools=4.61.1
  - freetype=2.14.1
  - icu=78.2
  - joblib=1.5.3
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.9
  - lcms2=2.18
  - lerc=4.0.0
  - libblas=3.11.0
  - libboost=1.88.0
  - libbrotlicommon=1.2.0
  - libbrotlidec=1.2.0
  - libbrotlienc=1.2.0
  - libcblas=3.11.0
  - libcxx=21.1.8
  - libdeflate=1.25
  - libexpat=2.7.3
  - libffi=3.5.2
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgcc=15.2.0
  - libgfortran=15.2.0
  - libgfortran5=15.2.0
  - libjpeg-turbo=3.1.2
  - liblapack=3.11.0
  - liblightgbm=4.6.0
  - liblzma=5.8.2
  - libopenblas=0.3.30
  - libpng=1.6.54
  - libsqlite=3.51.2
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=21.1.8
  - matplotlib=3.10.8
  - matplotlib-base=3.10.8
  - munkres=1.1.4
  - ncurses=6.5
  - numpy=2.2.6
  - opencl-headers=2025.06.13
  - openjpeg=2.5.4
  - openpyxl=3.1.5
  - openssl=3.6.1
  - packaging=26.0
  - pandas=2.3.3
  - pillow=12.1.0
  - pip=26.0.1
  - pthread-stubs=0.4
  - pyparsing=3.3.2
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.3
  - python_abi=3.10
  - pytz=2025.2
  - qhull=2020.2
  - readline=8.3
  - scikit-learn=1.7.2
  - scipy=1.15.2
  - setuptools=80.10.2
  - six=1.17.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - tornado=6.5.4
  - tzdata=2025c
  - unicodedata2=17.0.0
  - wheel=0.46.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - zlib-ng=2.3.3
  - zstd=1.5.7

prefix: "/Users/schenberg/miniforge3/envs/price_mvp"
